import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProfileMenu from "@/components/ProfileMenu";
import { Sidebar, SidebarBody, SidebarLink } from '@/components/ui/sidebar';
import { FiShoppingCart, FiHome, FiUsers, FiSettings, FiSearch, FiUser } from 'react-icons/fi';
import { LuUsers2 } from 'react-icons/lu';
import { IconBox } from '@tabler/icons-react';
import { GoGraph } from 'react-icons/go';
import ProductTable from "@/components/ProductTable";

const inter = Inter({ subsets: ["latin"] });


const links = [
  { label: 'Dashboard', href: '#', icon: <FiHome /> },
  { label: 'Orders', href: '#', icon: <FiShoppingCart /> },
  { label: 'Products', href: '#', icon: <IconBox /> },
  { label: 'Customers', href: './customers', icon: <LuUsers2 /> },
  { label: 'Analytics', href: '#', icon: <GoGraph /> },
];


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
     
          {children}
      
      </body>
    </html>
  );
}
